// GENERATED by scripts/fetch-movenet.mjs --emit-url-only. Do not edit.
// Points pose-detection at the bundled model so inference is
// network-free (ADR-004). The byte files live gitignored under
// public/pose/; regenerate with "npm run fetch:pose".
export const MOVENET_MODEL_URL = "/pose/movenet-singlepose-lite/model.json";
