// Downloads the MoveNet-SinglePose-Lite model once to assets/pose/. Run after
// fresh install:  `npm run fetch:pose`.
//
// Current state (2025): tfhub.dev 302-redirects to Kaggle and the old GCS
// `tfhub-public` bucket has been removed. If the download fails, hand-place the
// weights anywhere reachable and re-run.
//
// The model URL is written to `src/pose/modelUrl.ts` so the bundled copy is
// what `poseLoader` loads at runtime — ADR-004 ("fully local, no network").

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MODEL_DIR = path.join(ROOT, 'assets', 'pose', 'movenet-singlepose-lite');
const outUrl = path.join(ROOT, 'src', 'pose', 'modelUrl.ts');

const url =
    process.env.MOVENET_URL ??
        process.argv.find((a) => a.startsWith('http')) ??
         'https://tfhub.dev/google/tfjs-model/movenet/singlepose/lightning/4';

async function download(target, remote) {
   await fs.mkdir(path.dirname(target), { recursive: true });
   spawnSync('curl', ['-sSL', '--max-time', '90', '-f', '-o', target, remote], {
      stdio: 'inherit',
     });
     if(spawnSync('test', ['-s', target]).status !== 0) {
            throw new Error(`failed to download ${remote} → ${target}`);
        }
    }

async function main() {
   if(process.argv.includes('--emit-url-only')) {
      // Regenerate the loader file without downloading (used when the model was
      // hand-placed under assets/pose/).
      const served = '/assets/pose/movenet-singlepose-lite/model.json';
      const contents =
          '// GENERATED by scripts/fetch-movenet.mjs --emit-url-only. Do not edit.\n' +
           `// Points pose-detection at the bundled model so inference is\n` +
            `// network-free (ADR-004). The byte files live gitignored under\n` +
              `// assets/pose/; regenerate with "npm run fetch:pose".\n` +
                 `export const MOVENET_MODEL_URL = ${JSON.stringify(served)};\n`;
      await fs.mkdir(path.dirname(outUrl), { recursive: true });
      await fs.writeFile(outUrl, contents);
      console.log(`wrote ${outUrl}`);
       return;
       }
   console.log(`→ ${url}  →  ${path.relative(ROOT, MODEL_DIR)}/`);
      await download(path.join(MODEL_DIR, 'model.json'), url);
     // Pull each weights binary listed in model.json's manifest.
    const manifest = JSON.parse(await fs.readFile(path.join(MODEL_DIR, 'model.json'), 'utf8'));
    const weights = (manifest.weightsManifest ?? []).flatMap((g) => g.paths ?? []);
   for(const rel of weights) {
        const target = path.join(MODEL_DIR, rel);
        // `url` is the canonical URL; append the relative manifest path under
        // the same model directory.
      const remote = new URL(rel, `${url}/`).href;
       await download(target, remote);
        }
   // The Expo web asset path the loader uses. On web, Expo serves `public/`;
   // copy weights into public/ so they're reachable at a stable URL.
   const publicDir = path.join(ROOT, 'public', 'pose', 'movenet-singlepose-lite');
   const publicModel = path.join(publicDir, 'model.json');
   await fs.cp(MODEL_DIR, publicDir, { recursive: true });
      const served = '/pose/movenet-singlepose-lite/model.json';
     const contents =
        `// GENERATED by scripts/fetch-movenet.mjs. Do not edit.\n` +
          `// Points pose-detection at the bundled model under public/ for web.\n` +
            `// Native doesn't import this file (see providers.native split).\n` +
              `export const MOVENET_MODEL_URL = ${JSON.stringify(served)};\n`;
   await fs.mkdir(path.dirname(outUrl), { recursive: true });
   await fs.writeFile(outUrl, contents);
   console.log(`ok: ${publicModel} + ${weights.length} weight file(s); wrote ${outUrl}`);
    }

main().catch((e) => {
   console.error(`fetch-movenet: ${e.message}`);
   console.error(``);
   console.error(`tfhub.dev is known-dead as of 2025-09 (redirects to Kaggle). Options:`);
   console.error(`  1) Hand-place MoveNet-SinglePose-Lite graph in public/pose/movenet-singlepose-lite/`);
   console.error(`     then run:  node scripts/fetch-movenet.mjs --emit-url-only`);
   console.error(`  2) Pass a working mirror URL:  MOVENET_URL=https://... npm run fetch:pose`);
   console.error(`  3) Skip — the web studio degrades to manual placement (M2-4 path).`);
   process.exit(1);
});
